apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laxmivijay0706-bit/gitops-project.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laxmivijay0706-bit/gitops-project.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laxmivijay0706-bit/gitops-project.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
